openapi: 3.0.3
info:
  title: landmark area API
  description: landmark service
  version: "1.0"
paths:
  /administrative-areas:
    post:
      summary: Import areas
      operationId: importAdministrativeAreas
      tags:
        - administrativeArea
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                level:
                  $ref: "#/components/schemas/AdministrativeLevel"
                geometry:
                  $ref: "#/components/schemas/Geometry"
      responses:
        "400":
          description: Bad Request
        "201":
          description: Created
  /administrative-areas/{AdministrativeAreaId}:
    get:
      summary: display single administrative area
      operationId: loadAdministrativeArea
      tags:
        - administrativeArea
      parameters:
        - in: path
          name: AdministrativeAreaId
          required: true
          schema:
            type: AdministrativeAreaId
      responses:
        "400":
          description: Bad Request
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdministrativeArea"
    put:
      summary: update single administrative area
      operationId: updateAdministrativeArea
      tags:
        - administrativeArea
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdministrativeArea"
        required: true
      parameters:
        - in: path
          name: AdministrativeAreaId
          required: true
          schema:
            type: AdministrativeAreaId
      responses:
        "400":
          description: Bad Request
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdministrativeArea"
    delete:
      summary: delete single administrative area
      operationId: deleteAdministrativeArea
      tags:
        - administrativeArea
      parameters:
        - in: path
          name: AdministrativeAreaId
          required: true
          schema:
            type: AdministrativeAreaId
      responses:
        "400":
          description: Bad Request
        "204":
          description: OK
  /administrative-levels:
    post:
      summary: Create level
      operationId: createAdministrativeLevel
      tags:
        - administrativeLevel
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdministrativeLevel"
        required: true
      responses:
        "400":
          description: Bad Request
        "201":
          description: Created
  /administrative-levels/{AdministrativeLevelId}:
    get:
      summary: display single administrative level
      operationId: loadAdministrativeLevel
      tags:
        - administrativeLevel
      parameters:
        - in: path
          name: AdministrativeLevelId
          required: true
          schema:
            type: AdministrativeLevelId
      responses:
        "400":
          description: Bad Request
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdministrativeLevel"
    put:
      summary: update single administrative level
      operationId: updateAdministrativeLevel
      tags:
        - administrativeLevel
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdministrativeLevel"
        required: true
      parameters:
        - in: path
          name: AdministrativeLevelId
          required: true
          schema:
            type: AdministrativeLevelId
      responses:
        "400":
          description: Bad Request
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdministrativeLevel"
    delete:
      summary: delete single administrative level
      operationId: deleteAdministrativeLevel
      tags:
        - administrativeLevel
      parameters:
        - in: path
          name: AdministrativeLevelId
          required: true
          schema:
            type: AdministrativeLevelId
      responses:
        "400":
          description: Bad Request
        "204":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdministrativeLevel"
components:
  schemas:
    AdministrativeAreasImportRequest:
      type: object
      required:
        - level
      properties:
        level:
          $ref: "#/components/schemas/AdministrativeLevel"
    AdministrativeArea:
      type: object
      required:
        - name
        - level
      properties:
        id:
          type: AdministrativeAreaId
        name:
          type: LandmarkName
        createTime:
          type: string
          format: date-time
        updateTime:
          type: string
          format: date-time
        level:
          $ref: "#/components/schemas/AdministrativeLevel"
        parent:
          type: AdministrativeAreaId
        geometry:
          type: Geometry
        geometrySimplified:
          type: string
    AdministrativeLevel:
      type: object
      required:
        - order
        - country
        - name
      properties:
        id:
          type: AdministrativeLevelId
        name:
          type: LevelName
        createTime:
          type: string
          format: date-time
        updateTime:
          type: string
          format: date-time
        country:
          type: Country
        order:
          type: LevelOrder
    AdministrativeAreaId:
      type: string
    AdministrativeLevelId:
      type: string
    LandmarkName:
      type: string
    LevelName:
      type: string
    LevelOrder:
      type: integer
      format: int32
    Country:
      type: string
    Geometry:
      type: string
      format: binary
