openapi: 3.0.3
info:
  title: landmark area API
  description: landmark service
  version: "1.0"
paths:
  /landmarks:
    post:
      summary: Import landmark
      operationId: importLandmark
      tags:
        - landmark
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                landmark:
                  $ref: "#/components/schemas/Landmark"
                geometry:
                  $ref: "#/components/schemas/Geometry"
      responses:
        "400":
          description: Bad Request
        "201":
          description: Created
  /landmarks/{LandmarkId}:
    get:
      summary: display single landmark
      operationId: loadLandmark
      tags:
        - landmark
      parameters:
        - in: path
          name: LandmarkId
          required: true
          schema:
            type: LandmarkId
      responses:
        "400":
          description: Bad Request
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Landmark"
components:
  schemas:
    Landmark:
      type: object
      required:
        - geometryType
        - category
        - country
      properties:
        id:
          type: LandmarkId
        name:
          type: LandmarkName
        geometryType:
          type: LandmarkGeometryType
          example: POLYGON
        category:
          type: LandmarkCategory
          example: ADMINISTRATIVE_REGION
        country:
          type: Country
          example: CZECHIA
        loadTime:
          type: string
          format: date-time
        metadata:
          type: object
        parent:
          type: LandmarkId
    LandmarkId:
      type: string
    LandmarkName:
      type: string
    LandmarkGeometryType:
      type: string
    LandmarkCategory:
      type: string
    Country:
      type: string
    Geometry:
      type: string
      format: binary
