# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  liquibase:
    change-log: classpath:liquibase-changelog.xml
    defaultSchema: landmarks
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${MQ_HOST:localhost}
    port: ${MQ_PORT:5672}
    username: ${MQ_USERNAME:guest}
    password: ${MQ_PASSWORD:guest}

app:
  queue:
    landmark-queue: ${LANDMARK_QUEUE:landmark_queue}
  exchange:
    landmark-exchange: ${CYCLING_AREAS_EXCHANGE:cycling_areas_exchange}


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    urls[0]:
      url: /v3/api-docs
      name: landmarks


---
spring:
  config:
    activate:
      on-profile: default

server:
  port: 8080

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          jdbc:
            bind: TRACE
