/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package eu.cokeman.cycleareastats.openapi.api;

import eu.cokeman.cycleareastats.openapi.model.CountryDto;
import eu.cokeman.cycleareastats.openapi.model.CountryRequestDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Controller
@Tag(name = "country", description = "the country API")
public interface CountryApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /countries : add country
     *
     * @param countryRequestDto  (required)
     * @return country created (status code 201)
     */
    @Operation(
        operationId = "createCountry",
        summary = "add country",
        tags = { "country" },
        responses = {
            @ApiResponse(responseCode = "201", description = "country created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CountryDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/countries",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CountryDto> createCountry(
        @Parameter(name = "CountryRequestDto", description = "", required = true) @Valid @RequestBody CountryRequestDto countryRequestDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createTime\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"name\", \"updateTime\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /countries/{id} : delete country
     *
     * @param id  (required)
     * @return country deleted (status code 204)
     */
    @Operation(
        operationId = "deleteCountry",
        summary = "delete country",
        tags = { "country" },
        responses = {
            @ApiResponse(responseCode = "204", description = "country deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/countries/{id}"
    )
    default ResponseEntity<Void> deleteCountry(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /countries : fetch countries
     *
     * @return list of countries (status code 200)
     */
    @Operation(
        operationId = "getCountries",
        summary = "fetch countries",
        tags = { "country" },
        responses = {
            @ApiResponse(responseCode = "200", description = "list of countries", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = CountryDto.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/countries",
        produces = { "application/json" }
    )
    default ResponseEntity<List<CountryDto>> getCountries(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"createTime\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"name\", \"updateTime\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"\" }, { \"createTime\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"name\", \"updateTime\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /countries/{id} : fetch country by ID
     *
     * @param id  (required)
     * @return country desccription (status code 200)
     *         or country not found (status code 404)
     */
    @Operation(
        operationId = "getCountryById",
        summary = "fetch country by ID",
        tags = { "country" },
        responses = {
            @ApiResponse(responseCode = "200", description = "country desccription", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CountryDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "country not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/countries/{id}",
        produces = { "application/json" }
    )
    default ResponseEntity<CountryDto> getCountryById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createTime\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"name\", \"updateTime\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
