/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package eu.cokeman.cycleareastats.openapi.api;

import eu.cokeman.cycleareastats.openapi.model.LandmarkDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Controller
@Tag(name = "landmark", description = "the landmark API")
public interface LandmarkApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /landmarks : Import single landmark
     *
     * @param landmark  (optional)
     * @param geometry  (optional)
     * @return Bad Request (status code 400)
     *         or Created (status code 201)
     */
    @Operation(
        operationId = "importLandmark",
        summary = "Import single landmark",
        tags = { "landmark" },
        responses = {
            @ApiResponse(responseCode = "400", description = "Bad Request"),
            @ApiResponse(responseCode = "201", description = "Created")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/landmarks",
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<Void> importLandmark(
        @Parameter(name = "landmark", description = "") @Valid @RequestPart(value = "landmark", required = false) LandmarkDto landmark,
        @Parameter(name = "geometry", description = "") @RequestPart(value = "geometry", required = false) MultipartFile geometry
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /landmarks/{LandmarkId} : display single landmark
     *
     * @param landmarkId  (required)
     * @return Bad Request (status code 400)
     *         or OK (status code 200)
     */
    @Operation(
        operationId = "loadLandmark",
        summary = "display single landmark",
        tags = { "landmark" },
        responses = {
            @ApiResponse(responseCode = "400", description = "Bad Request"),
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LandmarkDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/landmarks/{LandmarkId}",
        produces = { "application/json" }
    )
    default ResponseEntity<LandmarkDto> loadLandmark(
        @Parameter(name = "LandmarkId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("LandmarkId") String landmarkId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"country\" : \"\", \"loadTime\" : \"2000-01-23T04:56:07.000+00:00\", \"metadata\" : \"{}\", \"name\" : \"\", \"id\" : \"\", \"category\" : \"\", \"geometryType\" : \"\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
